.sqlx/query-3aabbeae862994ed4bf90f24d6c7c5992c022ab53683b6a43d86d4ffd294fc79.json, src/job.rs, src/queue.rs, src/worker.rs
This allows tasks to be enqueued in a way that only makes them available after the specified delay. While tasks may already specify a delay, that configuration is static whereas this method allows for dynamic delays in accordance with runtime requirements.
=> provide enqueue_after method

.sqlx/query-45b1b27f9669db53892c4cfad7d09c0e325cfacbf1c37589300fb48e8d9eac49.json, .sqlx/query-54d124a54b2bb28f85b3ee9882f1e103d8e690ea0cb5189411834b9d8b246fc4.json, Cargo.toml, src/queue.rs, src/worker.rs
This introduces a mechanism for politely asking Underway to shutdown. To do so, a new function, `graceful_shutdown` is provided. Calling this function will send a notification to a Postgres channel. Workers listen on this channel and when a message is received will stop processing new tasks. If they're already processing a task, then they wait until that task is done or the task timeout has elapsed, whichever is first.
In order to cleanly stop the queue, this function should be used. If stopping in-progress tasks is safe for your use case, then this can be ignored and the queue can be stopped without any delay.
Closes #5
=> provide graceful shutdown interface

src/job.rs, src/lib.rs, src/scheduler.rs, src/worker.rs
This adds a facility for setting shared state on jobs via the `state` method on the job builder. When state is provided, the execute function must accept input and state, in that order, as arguments.
Shared state is useful in a number of ways, including when resources like database pools, should be accessible to your jobs.
Furthermore, patterns like `Arc<Mutex<T>>` enable shared mutable state, where necessary.
=> provide stateful jobs

src/lib.rs, src/task.rs
This introduces a new trait, ToTaskResult, which makes it easier to convert results in execute futures to either retryable or fatal errors.
More specifically it provides two methods:
1. retryable
2. fatal
Which are implemented for Result where the error type implements Display.
When ToTaskResult is in scope, these methods will be available on results that meet its requirements and allow callers to ergonomically declare the desired conversion.
=> provide trait for converting to task results

examples/graceful_shutdown/src/main.rs, examples/scheduled/src/main.rs, src/job.rs
This changes the way the run method works on jobs: now both the scheduler and the worker will be spawned off into separate tasks and selected over.
Additionally a new run_worker method is provided as a convenience, which is the complement to run_scheduler.
By doing so, in-process task execution is simplified when using scheduled jobs.
=> run both scheduler and worker for jobs

examples/multitask/Cargo.toml, examples/multitask/src/main.rs
This is an illustration of how `Task` may be implemented for a struct which itself contains other implementations of `Task`.
Doing so allows multiple tasks to co-exist in the same queue and be processed by the same worker all while maintaining type safety.
=> provide multitask example

src/job.rs, src/queue.rs, src/task.rs, src/task/retry_policy.rs
This is technically a breaking change, but cleans up the conventions and provides improved organization.
=> rename all builders as "builder"

.sqlx/query-05abadcb1abc6591d8b59bffd7cfe7a40ce6e5d935d34bb377e204acef918ab1.json, .sqlx/query-33d2dc54f81632a9b55321669436ecbeac7376c73197b52458b5a2af4f9dbf63.json, Cargo.toml, README.md, examples/basic/src/main.rs, examples/graceful_shutdown/src/main.rs, examples/multitask/src/main.rs, examples/scheduled/src/main.rs, examples/step/Cargo.toml, examples/step/src/main.rs, examples/tracing/src/main.rs, src/job.rs, src/lib.rs, src/queue.rs, src/scheduler.rs, src/task.rs, src/worker.rs
This introduces step functions.
Step functions are a series of linked tasks where each task takes input from the output of previous one. Said another way, step functions are a chain of dependent tasks, each depending on its immediate ancestor. 
This design makes it possible to define a series of discrete tasks that can perform work which is required for further work as the series progresses. What this means is that when tasks fail and are retried, prior work is not repeated.
With this patch jobs are now composed of one or more step functions.
Enabling this interface also necessitates updating tasks to:
1. Provide an output as an associated type and,
2. Take a transaction as input to their execute method.
It's worth noting that various breaking changes are contained throughout and this is …
=> Step functions

migrations/20241024174106_1.sql, src/job.rs, src/worker.rs
This introduces a trigger which will notify a channel when tasks are inserted or updated in a "pending" state. Workers now listen on this channel and if their queue is named as the one the notification is for begin processing the next task.
Because channel notifications can fail, we retain the polling mechanism only now it's set to a default polling interval of one minute. This can be configured to be shorter or longer as well.
Closes #19
=> use channels to process ready tasks

Cargo.toml, examples/graceful_shutdown/src/main.rs, src/worker.rs
This refactors worker shutdown to use a cancellation token to signal shutdown. By doing so, we can avoid managing an atomic bool. It also makes it possible to provide addtional methods, such as a `shutdown` method, on the worker itself to signal shutdown.
=> use cancellation token for shutdown

examples/basic/src/main.rs, examples/multitask/src/main.rs, examples/step/src/main.rs, examples/tracing/src/main.rs, src/job.rs, src/lib.rs, src/queue.rs, src/scheduler.rs, src/worker.rs
This refactors the scheduler to be more like the worker: e.g. it now manages a cancellation token and uses it to manage the shutdown state.
Again similarly to the worker, it listens on the same shutdown channel and upon a notify from postgres will cancel its cancellation token thereby stopping the scheduler.
Coupled with these changes is a breaking change to the queue interface: instead of taking ownership of input, enqueue takes a reference. A similar change should be made for the schedule methods, but that is left out of this patch intentionally.
=> refactor scheduler

examples/graceful_shutdown/src/main.rs, examples/scheduled/src/main.rs, src/job.rs, src/lib.rs, src/queue.rs
This is a follow up to the enqueue changes in #33.
=> also make schedule methods pass input by reference

src/job.rs, src/scheduler.rs, src/worker.rs
This provides a shutdown method for jobs via a new "job handle". Handles encapsulate the worker and scheduler tasks as well as a cancellation token that's passed down to the worker and scheduler.
We also introduce a method for setting the shutdown token on both the worker and scheduler.
=> shutdown method for jobs

.sqlx/query-03c2ac38e6ec2801eed7e5b19076eafcc589f32e2424460b0c345e6c477a1b28.json, .sqlx/query-2584080f8ca262aa7526dde00a50ae125a6a8e52f4fc76d05d15f2c6f663d1cd.json, .sqlx/query-ccf314910c001d4933326838f507380d36a50d63778ed5589d7ffe0fe9f60db3.json, .sqlx/query-f069227d261bdec30ade8d0553bffc2796c3f4914f773ef569526feb0c7062ea.json, README.md, examples/basic/src/main.rs, examples/graceful_shutdown/src/main.rs, examples/multitask/src/main.rs, examples/rag/src/main.rs, examples/scheduled/src/main.rs, examples/step/src/main.rs, examples/tracing/src/main.rs, migrations/20240921151751_0.sql, src/lib.rs
This is something of a hack to work around the fact that SQLx migrations do not currently support specifying a schema under which the migrations table will live.
Here we provide a search path throughout our migrations and in the transaction that will run the migrations to ensure that migrations are applied to `underway._sqlx_migrations`. Note that this assumes a `public._sqlx_migrations` exists.
In the future we should be able to use `sqlx.toml` to address this more robustly. That's expected as part of the `0.9.0` release of SQLx. Please see: https://github.com/launchbadge/sqlx/pull/3383
Closes #11
=> isolate underway migrations

.sqlx/query-0d302d44aacf1e8ee3233b8c4814e7355fc4b57d98550cd43aec5c424ac4cdca.json, .sqlx/query-2692ae7a5cce9ed6fb444259dce61d6cc4b34794d25cdbc3eec820abd807de00.json, src/job.rs, src/queue.rs
This introduces a type that's returned from enqueuing a job and specifically replaces the task ID. By doing so, we also enable job cancellation.
Additional methods, providing e.g. deletion or resumption, can be added in future as well.
Lastly `Future` could be implemented for this type. Assuming an implementation that polls the status of the job's completion, this could be optionally awaited to ensure a specific job has reached a completed state.
=> provide an enqueued job type

.sqlx/query-a55bfd24f1ca171d27491593b8e96d78ee50e376d08e1a7a873048d7468638d8.json, .sqlx/query-c3b4d8c60a953915625f12731554c46ae4ae17bc0d01d91a214da652b2535f58.json, .sqlx/query-e6a0949430cf67fb2452bf41533d402338b3afbbef23785c8460ecc2c00cd5a3.json, src/job.rs, src/queue.rs, src/task.rs, src/worker.rs
Following from changes to the job ID, here we make the task ID as a newtype.
=> use newtype for task id

.sqlx/query-167170ec018c32a7c9238ab95490dccb8d22d4591ba8920691213829c0a11622.json, .sqlx/query-24e7b0c00cda5634d04fe27cb833f12803108d0b4235d39fe372acd4b364d99d.json, .sqlx/query-9731fc6ba31c2cc1bd00b8e177c44ca85285a2606f9485a9f38a3585ce48b00b.json, .sqlx/query-98aa8d56e8fb6d28480105370b0b6a6d3e68e0e64bdeeed97a04e7597aa43853.json, .sqlx/query-d726027de5fc4369abc0bc76f0ce0ec74f97447850cebdebba1c0748059ce17e.json, migrations/20241110164319_3.sql, src/job.rs, src/queue.rs, src/task.rs, src/worker.rs
This refactor encapsulates pending task dequeue operations within their own transactions, updating the task row state to prevent duplicate processing by other callers. By doing so, we ensure that state changes are immediately visible, accurately reflecting task ownership throughout its processing lifecycle.
Additionally, tasks now include a configurable heartbeat interval and a record of the last heartbeat. Workers periodically update the task row to indicate ongoing liveness. Should a task’s heartbeat become stale, the dequeue method can select it for reassignment.
It's important to note that a missed heartbeat alone does not definitively indicate task abandonment, as a worker might resume processing after a temporary delay. To guard against this type of partial failure, workers also …
=> refactor dequeue transaction handling

src/queue.rs, src/worker.rs
This fixes an issue where we were:
1. Not using an interval and therefore only waiting one time to send a heartbeat,
2. Cancelling the other select futures as a side effect of incorporating the heartbeat.
So to address these issues, we use a separate task entirely to record heartbeats.
=> record heartbeat in a separate task

.sqlx/query-56a0f6c70e41d1b89d0b16a4cbbb989aa3da718f76f4f4abf8794e538c4ed2b8.json, .sqlx/query-910aaa339267667a5184c82f628b2f744c70fce710c52ea542f38eff0d7100e5.json, .sqlx/query-a288070a7d1f34fd78d382dc3757557b3f674dd9c46067ed80232cbfbbd56a98.json, src/queue.rs
This fixes an issue where dequeuing a stall retry would not consider if the related task had available retries or not.
To address this we rework the dequeue query to check the retry record directly as part of the condition for selecting a stale task.
We also provide an update over attempt rows when a task row is selected to ensure that prior in-progress attempts are marked as failed.
=> stale dequeues consider retries

Cargo.toml, src/scheduler.rs
This refactors the scheduler iterator into its own type which manages the upcoming schedule directly.
=> refactor scheduler iterator

src/worker.rs
This fixes an issue where the heartbeat spawned task would continue to run indefinitely, even after execution had been completed. We address this by incorporating the join handle as a select branch, ensuring that the future is cancelled when either the execution finishes or it times out.
=> ensure heartbeat task is cancelled after execution

.sqlx/query-7513f95eb46920c91e32cf7dac34155bbaac4ee4a5011c110df702eab4c8e03f.json, src/job.rs
Since we select and then update a set of tasks in a transaction in order to cancel pending tasks relative to a given job, we should also hold a lock over that selection via `for update`.
=> ensure job cancellation selection holds a lock

src/lib.rs
This provides some additional documentation that details the way the "lower-level" Underway system interfaces with the "higher-level" system.
A simple diagram is also included to help visualize the relationship between components.
=> document lower- and higher-level systems

migrations/20241126224448_5.sql
This reorders the task and task_attempt primary keys such that the queue name prefixes the index name. Because queues are contained within the same physical table, this prefix helps ensure better performance when selecting tasks from the queue.
Closes #68
=> reorder task and task_attempt primary key
